spring.application.name=siontrack
server.port=8081

# Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/SionTrackDB?currentSchema=siontrack
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate

# Seguridad (será ignorado por SecurityConfig, pero lo dejamos por claridad)
spring.security.user.name=admin
spring.security.user.password=admin123

spring.jmx.enabled=true

# Thymeleaf (¡Esta es la única línea que realmente necesitamos para desarrollo!)
# Deshabilita la caché de Thymeleaf para ver los cambios de HTML al instante.
spring.thymeleaf.cache=false


#Configuraciones de WhatsApp
whatsapp.token-acceso=EAARfbc7DIZBIBQZCsYQo3d1B0uxFhPZB10HJ1TmADvWYqWh61pIHRnPZB9p32En6cdrrZCMOjYKeUdk6dc9g53agtwHBU091TvrEjN729uvFZCZBCZCpVZCl3XFfUI0rUdQNKg4fRwZAi6DRVF3QzrK1wPkNGEcH8bdOAF4VfpRrLomZCJqf8f2tvs1rS2gbq4eMFm2i9ACzRCeswILYeWnLpQ34OroeggROKiqqVcbG5zepy1ZBT4bLffgCORVaAW8NOFaJnwYRpxzk7RreIZBs2xXltqqMeOQZDZD
whatsapp.i-d-numero=1015318861657309
whatsapp.codigo-pais=57
whatsapp.api-version=v22.0

whatsapp.webhook.tokenverificacion=token_provisional_siontrack

whatsapp.plantillas.consentimiento=solicitud_consentimiento
whatsapp.plantillas.recordatorio=recordatorio_mantenimiento
whatsapp.plantillas.promocion=promociones
whatsapp.plantillas.idioma=es
