spring.application.name=siontrack
server.port=${PORT:8081}

# Base de Datos - Cloud SQL Auth Proxy
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.cloud.gcp.sql.instance-connection-name=${INSTANCE_CONNECTION_NAME}
spring.cloud.gcp.sql.database-name=${DATABASE_NAME}
spring.jpa.properties.hibernate.default.schema=${DATABASE_SCHEMA}
spring.jpa.hibernate.ddl-auto=validate

# Thymeleaf
spring.thymeleaf.cache=true

# Configuraciones de WhatsApp
whatsapp.token-acceso=${WHATSAPP_TOKEN_ACCESO}
whatsapp.i-d-numero=${WHATSAPP_ID_NUMERO}
whatsapp.codigo-pais=57
whatsapp.api-version=v22.0
whatsapp.webhook.tokenverificacion=${WHATSAPP_WEBHOOK_TOKEN}

# Plantillas
whatsapp.plantillas.consentimiento=solicitud_consentimiento
whatsapp.plantillas.recordatorio=recordatorio_mantenimiento
whatsapp.plantillas.promocion=promociones
whatsapp.plantillas.idioma=es

# Monitoreo
management.endpoints.web.exposure.include=health,metrics,info