spring.application.name=siontrack
server.port=8081

# Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/SionTrackDB?currentSchema=siontrack
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate

# Seguridad (será ignorado por SecurityConfig, pero lo dejamos por claridad)
spring.security.user.name=admin
spring.security.user.password=admin123

spring.jmx.enabled=true

# Thymeleaf (¡Esta es la única línea que realmente necesitamos para desarrollo!)
# Deshabilita la caché de Thymeleaf para ver los cambios de HTML al instante.
spring.thymeleaf.cache=false


#Configuraciones de WhatsApp
whatsapp.token-acceso=EAARfbc7DIZBIBQ6sWYZCRBWIZCQFBAriZAgZCuzZCLONtyAgeZAWxSGrZAGF4Er3i6sgoireLse8Y8vywuk54dZC1mOyeUW1dbO1j1UAoqhw2DQCT3Ric7D2DTc1YjQh1lpnhznkuZB3OOvn1fqAf1SFpCXdPi3xHwOx2jZBZCY9YBcxom1absm8yHeaZBgqAtdRBaXSne7YyIVo8O4NY7tp85PShIDD3mWDFrQvZBlpEcRIwZCBOYFbXLrAW3w3qfsxZCcRmI7ZAPiuWUYiGIBnhPu2iyQ7mBsuB
whatsapp.i-d-numero=1015318861657309
whatsapp.codigo-pais=57
whatsapp.api-version=v22.0

whatsapp.webhook.tokenverificacion=token_provisional_siontrack

whatsapp.plantillas.consentimiento=solicitud_consentimiento
whatsapp.plantillas.recordatorio=recordatorio_mantenimiento
whatsapp.plantillas.promocion=promociones
whatsapp.plantillas.idioma=es
